# Application name
spring:
  application:
    name: MpesaB2C

  # DataSource configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  # JPA configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  # H2 console configuration
  h2:
    console:
      enabled: true

  # Kafka configuration
  kafka:
    bootstrap-servers: localhost:9092

  server:
    port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

mpesa:
  daraja:
    oauth-endpoint: https://sandbox.safaricom.co.ke/oauth/v1/generate
    register-url-endpoint: https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl
    grant-type: client_credentials
    shortCode: 600584
    confirmationURL: https://622a-41-72-192-18.ngrok-free.app/mobile-money/confirmation
    validationURL: https://622a-41-72-192-18.ngrok-free.app/mobile-money/validation
    responseType: Completed
    b2c-transaction-endpoint: https://sandbox.safaricom.co.ke/mpesa/b2c/v1/paymentrequest
    b2c-result-url: https://622a-41-72-192-18.ngrok-free.app/mobile-money/transaction-result
    b2c-queue-timeout-url: https://622a-41-72-192-18.ngrok-free.app/mobile-money/b2c-queue-timeout
    b2c-initiator-name: testapi
    b2c-initiator-password: Safaricom999!*!
    transactionResultUrl: https://sandbox.safaricom.co.ke/mpesa/transactionstatus/v1/query

